// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TConfigConfiguration : IEntityTypeConfiguration<TConfig>
    {
        public void Configure(EntityTypeBuilder<TConfig> entity)
        {
            entity.HasKey(e => e.ConfigId).HasName("PK_T_CONFIG__Id");

            entity.ToTable("T_CONFIG");

            entity.Property(e => e.ConfigId).HasColumnName("CONFIG_ID");
            entity.Property(e => e.ConfigDaysToKeepAcuoAudits)
                .HasDefaultValue(30)
                .HasColumnName("CONFIG_DAYS_TO_KEEP_ACUO_AUDITS");
            entity.Property(e => e.ConfigDaysToKeepAudits)
                .HasDefaultValue(30)
                .HasColumnName("CONFIG_DAYS_TO_KEEP_AUDITS");
            entity.Property(e => e.ConfigDaysToKeepDeletedImages)
                .HasDefaultValue(30)
                .HasColumnName("CONFIG_DAYS_TO_KEEP_DELETED_IMAGES");
            entity.Property(e => e.ConfigDaysToKeepUserAudits).HasColumnName("CONFIG_DAYS_TO_KEEP_USER_AUDITS");
            entity.Property(e => e.ConfigDeletionVerificationRequired).HasColumnName("CONFIG_DELETION_VERIFICATION_REQUIRED");
            entity.Property(e => e.ConfigManualDeletionOnly).HasColumnName("CONFIG_MANUAL_DELETION_ONLY");
            entity.Property(e => e.ConfigMinutesToKeepSyslogTasks)
                .HasDefaultValue(1440)
                .HasColumnName("CONFIG_MINUTES_TO_KEEP_SYSLOG_TASKS");
            entity.Property(e => e.ConfigSecondsToCheckForSyslogAudits)
                .HasDefaultValue(5)
                .HasColumnName("CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_AUDITS");
            entity.Property(e => e.ConfigSecondsToCheckForSyslogChanges)
                .HasDefaultValue(10)
                .HasColumnName("CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_CHANGES");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TConfig> entity);
    }
}
