// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TUpgradeHistoryConfiguration : IEntityTypeConfiguration<TUpgradeHistory>
    {
        public void Configure(EntityTypeBuilder<TUpgradeHistory> entity)
        {
            entity.HasKey(e => e.HstIdentity).HasName("PK_T_UPGRADE_HISTORY__Identity");

            entity.ToTable("T_UPGRADE_HISTORY");

            entity.Property(e => e.HstIdentity).HasColumnName("HST_Identity");
            entity.Property(e => e.HstByUser)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("HST_By_User");
            entity.Property(e => e.HstComment)
                .HasMaxLength(100)
                .HasColumnName("HST_Comment");
            entity.Property(e => e.HstNewBuild).HasColumnName("HST_New_Build");
            entity.Property(e => e.HstNewDbSize)
                .HasDefaultValue(-1L)
                .HasColumnName("HST_New_DbSize");
            entity.Property(e => e.HstNewMajor).HasColumnName("HST_New_Major");
            entity.Property(e => e.HstNewMinor).HasColumnName("HST_New_Minor");
            entity.Property(e => e.HstNewSp).HasColumnName("HST_New_SP");
            entity.Property(e => e.HstNewStatus).HasColumnName("HST_New_Status");
            entity.Property(e => e.HstOldBuild).HasColumnName("HST_Old_Build");
            entity.Property(e => e.HstOldDbSize)
                .HasDefaultValue(-1L)
                .HasColumnName("HST_Old_DbSize");
            entity.Property(e => e.HstOldMajor).HasColumnName("HST_Old_Major");
            entity.Property(e => e.HstOldMinor).HasColumnName("HST_Old_Minor");
            entity.Property(e => e.HstOldSp).HasColumnName("HST_Old_SP");
            entity.Property(e => e.HstOldStatus).HasColumnName("HST_Old_Status");
            entity.Property(e => e.HstSqledition)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("HST_SQLEdition");
            entity.Property(e => e.HstSqlinstance)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("HST_SQLInstance");
            entity.Property(e => e.HstSqllevel)
                .IsRequired()
                .HasMaxLength(5)
                .HasColumnName("HST_SQLLevel");
            entity.Property(e => e.HstSqlmachine)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("HST_SQLMachine");
            entity.Property(e => e.HstSqlversion)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("HST_SQLVersion");
            entity.Property(e => e.HstState).HasColumnName("HST_State");
            entity.Property(e => e.HstUtcEndDate)
                .HasColumnType("datetime")
                .HasColumnName("HST_UtcEndDate");
            entity.Property(e => e.HstUtcStartDate)
                .HasColumnType("datetime")
                .HasColumnName("HST_UtcStartDate");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TUpgradeHistory> entity);
    }
}
