// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TUpgradeDetailConfiguration : IEntityTypeConfiguration<TUpgradeDetail>
    {
        public void Configure(EntityTypeBuilder<TUpgradeDetail> entity)
        {
            entity.HasKey(e => e.DtlIdentity).HasName("PK_T_UPGRADE_DETAIL__Identity");

            entity.ToTable("T_UPGRADE_DETAIL");

            entity.HasIndex(e => new { e.DtlTask, e.DtlHstIdentity }, "IX_T_UPGRADE_DETAIL__Task_HSTIdentity").HasFillFactor(100);

            entity.Property(e => e.DtlIdentity).HasColumnName("DTL_Identity");
            entity.Property(e => e.DtlHstIdentity).HasColumnName("DTL_HST_Identity");
            entity.Property(e => e.DtlRetry).HasColumnName("DTL_Retry");
            entity.Property(e => e.DtlTask)
                .HasMaxLength(255)
                .HasColumnName("DTL_Task");
            entity.Property(e => e.DtlUtcEndDate)
                .HasColumnType("datetime")
                .HasColumnName("DTL_UtcEndDate");
            entity.Property(e => e.DtlUtcStartDate)
                .HasColumnType("datetime")
                .HasColumnName("DTL_UtcStartDate");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TUpgradeDetail> entity);
    }
}
