// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Acuo.IHEAudit.DAL.Models;

namespace Acuo.IHEAudit.DAL.Models
{
    public partial class AcuoMedIHEAuditContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
