// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acuo.IHEAudit.DAL.Models
{
    public partial class SP_AUDITS_DELETE_ACUO_AUDITSResult
    {
        public int AL_ID { get; set; }
        public DateTime AL_AUDIT_DATE { get; set; }
        public string AL_EVENT_TYPE { get; set; }
        public string AL_USER { get; set; }
        public string AL_PT_ID { get; set; }
        public string AL_PT_NAME { get; set; }
        public string AL_ST_DICOM_UID { get; set; }
        public string AL_SE_MODALITY { get; set; }
        public string AL_SE_DICOM_UID { get; set; }
        public string AL_IM_SOPINSTANCE_UID { get; set; }
        public string AL_FILE_NAME { get; set; }
        public string AL_SOURCE { get; set; }
        public string AL_MACHINE { get; set; }
        public string AL_DATABASE { get; set; }
        public string AL_COMMENT { get; set; }
        public Guid? AL_IHE_ID { get; set; }
        public string AL_ACCESSION_NUMBER { get; set; }
        public string AL_ACUOSTORE_SERVER_NAME { get; set; }
        public string AL_ACUOSTORE_APPLICATION_NAME { get; set; }
        public string AL_ACUOSTORE_USER_NAME { get; set; }
        public string AL_ACUOSTORE_USER_PASSWORD { get; set; }
        public byte[] AL_RECYCLE_BIN_FOLDER { get; set; }
        public byte[] AL_IMAGE_GUID { get; set; }
        public string AL_DELETION_SET_ID { get; set; }
        public bool AL_VERIFIED_FOR_DELETION { get; set; }
        public DateTime? AL_RESTORED_LAST_DATE { get; set; }
        public string AL_RESTORED_SERVER { get; set; }
        public int? AL_RESTORED_PORT { get; set; }
        public string AL_RESTORED_AE_NAME { get; set; }
        public bool AL_RESTORE { get; set; }
    }
}
