// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TIheAudit
{
    public Guid IheAuditId { get; set; }

    public DateTime IheLocalDate { get; set; }

    public int IheSyslogSeverity { get; set; }

    public int IheEventId { get; set; }

    public int? IheEventType { get; set; }

    public string IheEventAction { get; set; }

    public byte[] IheXmlMessage { get; set; }

    public bool IheVerifiedForDeletion { get; set; }
}