// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TUpgradeBitmask
{
    public string MskKeyWord { get; set; }

    public string MskDescription { get; set; }

    public int MskKeyType { get; set; }

    public int MskMaskInteger { get; set; }
}