// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TUpgradeDetail
{
    public int DtlIdentity { get; set; }

    public int DtlHstIdentity { get; set; }

    public DateTime DtlUtcStartDate { get; set; }

    public DateTime DtlUtcEndDate { get; set; }

    public string DtlTask { get; set; }

    public short DtlRetry { get; set; }
}