// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TUserAudit
{
    public Guid UaaAuditId { get; set; }

    public DateTime UaaAuditDate { get; set; }

    public short? UaaAuditLevel { get; set; }

    public short? UaaAuditAction { get; set; }

    public string UaaUserDomain { get; set; }

    public string UaaUser { get; set; }

    public string UaaPtId { get; set; }

    public string UaaPtName { get; set; }

    public string UaaStDicomUid { get; set; }

    public string UaaStAccessionNumber { get; set; }

    public string UaaSeDicomUid { get; set; }

    public string UaaImDicomUid { get; set; }

    public string UaaQueryString { get; set; }

    public Guid? UaaIheAudit { get; set; }

    public bool UaaVerifiedForDeletion { get; set; }
}