// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TVersionVer
{
    public int VerMajor { get; set; }

    public int VerMinor { get; set; }

    public int VerRevision { get; set; }

    public int VerBuildnumber { get; set; }
}