// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TEventConfiguration : IEntityTypeConfiguration<TEvent>
    {
        public void Configure(EntityTypeBuilder<TEvent> entity)
        {
            entity.HasKey(e => new { e.EvId, e.EvType }).HasName("PK_T_EVENTS__Id_Type");

            entity.ToTable("T_EVENTS");

            entity.Property(e => e.EvId).HasColumnName("EV_ID");
            entity.Property(e => e.EvType).HasColumnName("EV_TYPE");
            entity.Property(e => e.EvCodeSystem)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("EV_CODE_SYSTEM");
            entity.Property(e => e.EvIdDescription)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("EV_ID_DESCRIPTION");
            entity.Property(e => e.EvLogCreate).HasColumnName("EV_LOG_CREATE");
            entity.Property(e => e.EvLogCreateSupport).HasColumnName("EV_LOG_CREATE_SUPPORT");
            entity.Property(e => e.EvLogDelete).HasColumnName("EV_LOG_DELETE");
            entity.Property(e => e.EvLogDeleteSupport).HasColumnName("EV_LOG_DELETE_SUPPORT");
            entity.Property(e => e.EvLogExecute).HasColumnName("EV_LOG_EXECUTE");
            entity.Property(e => e.EvLogExecuteSupport).HasColumnName("EV_LOG_EXECUTE_SUPPORT");
            entity.Property(e => e.EvLogRead).HasColumnName("EV_LOG_READ");
            entity.Property(e => e.EvLogReadSupport).HasColumnName("EV_LOG_READ_SUPPORT");
            entity.Property(e => e.EvLogUpdate).HasColumnName("EV_LOG_UPDATE");
            entity.Property(e => e.EvLogUpdateSupport).HasColumnName("EV_LOG_UPDATE_SUPPORT");
            entity.Property(e => e.EvTypeDescription)
                .HasMaxLength(50)
                .HasColumnName("EV_TYPE_DESCRIPTION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TEvent> entity);
    }
}
