// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TIheAuditConfiguration : IEntityTypeConfiguration<TIheAudit>
    {
        public void Configure(EntityTypeBuilder<TIheAudit> entity)
        {
            entity.HasKey(e => e.IheAuditId)
                .HasName("PK_T_IHE_AUDIT__AuditId")
                .IsClustered(false);

            entity.ToTable("T_IHE_AUDIT");

            entity.HasIndex(e => e.IheLocalDate, "IX_T_IHE_AUDIT__LocalDate")
                .IsClustered()
                .HasFillFactor(100)
                .HasStorageParameter("fillfactor", 100);

            entity.Property(e => e.IheAuditId)
                .ValueGeneratedNever()
                .HasColumnName("IHE_AUDIT_ID");
            entity.Property(e => e.IheEventAction)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("IHE_EVENT_ACTION");
            entity.Property(e => e.IheEventId).HasColumnName("IHE_EVENT_ID");
            entity.Property(e => e.IheEventType).HasColumnName("IHE_EVENT_TYPE");
            entity.Property(e => e.IheLocalDate)
                .HasColumnType("datetime")
                .HasColumnName("IHE_LOCAL_DATE");
            entity.Property(e => e.IheSyslogSeverity).HasColumnName("IHE_SYSLOG_SEVERITY");
            entity.Property(e => e.IheVerifiedForDeletion).HasColumnName("IHE_VERIFIED_FOR_DELETION");
            entity.Property(e => e.IheXmlMessage)
                .IsRequired()
                .HasColumnType("image")
                .HasColumnName("IHE_XML_MESSAGE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TIheAudit> entity);
    }
}
