// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TSyslogConfiguration : IEntityTypeConfiguration<TSyslog>
    {
        public void Configure(EntityTypeBuilder<TSyslog> entity)
        {
            entity.HasKey(e => e.RsId).HasName("PK_T_SYSLOG__Id");

            entity.ToTable("T_SYSLOG");

            entity.Property(e => e.RsId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("RS_ID");
            entity.Property(e => e.RsClientCert)
                .HasMaxLength(255)
                .HasColumnName("RS_CLIENT_CERT");
            entity.Property(e => e.RsHostid)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("RS_HOSTID");
            entity.Property(e => e.RsPause).HasColumnName("RS_PAUSE");
            entity.Property(e => e.RsPort).HasColumnName("RS_PORT");
            entity.Property(e => e.RsServerCert)
                .HasMaxLength(255)
                .HasColumnName("RS_SERVER_CERT");
            entity.Property(e => e.RsTlsEnabled).HasColumnName("RS_TLS_ENABLED");
            entity.Property(e => e.RsType)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("RS_TYPE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TSyslog> entity);
    }
}
