// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TTaskConfiguration : IEntityTypeConfiguration<TTask>
    {
        public void Configure(EntityTypeBuilder<TTask> entity)
        {
            entity.HasKey(e => e.TaskId).HasName("PK_T_TASKS__Id");

            entity.ToTable("T_TASKS");

            entity.HasIndex(e => new { e.TaskTargetId, e.TaskIheAuditId }, "IX_T_TASKS__TargetId_IheAuditId")
                .HasFillFactor(90)
                .HasStorageParameter("fillfactor", 100);

            entity.Property(e => e.TaskId).HasColumnName("TASK_ID");
            entity.Property(e => e.TaskIheAuditId).HasColumnName("TASK_IHE_AUDIT_ID");
            entity.Property(e => e.TaskLastError)
                .HasMaxLength(255)
                .HasColumnName("TASK_LAST_ERROR");
            entity.Property(e => e.TaskQueuedTime)
                .HasColumnType("datetime")
                .HasColumnName("TASK_QUEUED_TIME");
            entity.Property(e => e.TaskRunCount).HasColumnName("TASK_RUN_COUNT");
            entity.Property(e => e.TaskStatus).HasColumnName("TASK_STATUS");
            entity.Property(e => e.TaskTargetId).HasColumnName("TASK_TARGET_ID");
            entity.Property(e => e.TaskXmlMessage)
                .IsRequired()
                .HasDefaultValueSql("(0x00)")
                .HasColumnType("image")
                .HasColumnName("TASK_XML_MESSAGE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TTask> entity);
    }
}
