// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TUpgradeBitmaskConfiguration : IEntityTypeConfiguration<TUpgradeBitmask>
    {
        public void Configure(EntityTypeBuilder<TUpgradeBitmask> entity)
        {
            entity.HasKey(e => e.MskKeyWord).HasName("PK_T_UPGRADE_BITMASK__KeyWord");

            entity.ToTable("T_UPGRADE_BITMASK");

            entity.Property(e => e.MskKeyWord)
                .HasMaxLength(40)
                .HasColumnName("MSK_KeyWord");
            entity.Property(e => e.MskDescription)
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnName("MSK_Description");
            entity.Property(e => e.MskKeyType).HasColumnName("MSK_KeyType");
            entity.Property(e => e.MskMaskInteger).HasColumnName("MSK_MaskInteger");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TUpgradeBitmask> entity);
    }
}
