// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TUserAuditConfiguration : IEntityTypeConfiguration<TUserAudit>
    {
        public void Configure(EntityTypeBuilder<TUserAudit> entity)
        {
            entity.HasKey(e => e.UaaAuditId);

            entity.ToTable("T_USER_AUDIT");

            entity.HasIndex(e => new { e.UaaAuditDate, e.UaaVerifiedForDeletion }, "IX_T_USER_AUDIT__AuditDate_Verified").IsDescending(false, true);

            entity.HasIndex(e => e.UaaPtId, "IX_T_USER_AUDIT__PatientId");

            entity.HasIndex(e => e.UaaPtName, "IX_T_USER_AUDIT__PatientName");

            entity.HasIndex(e => e.UaaUser, "IX_T_USER_AUDIT__User");

            entity.Property(e => e.UaaAuditId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("UAA_AUDIT_ID");
            entity.Property(e => e.UaaAuditAction).HasColumnName("UAA_AUDIT_ACTION");
            entity.Property(e => e.UaaAuditDate)
                .HasColumnType("datetime")
                .HasColumnName("UAA_AUDIT_DATE");
            entity.Property(e => e.UaaAuditLevel).HasColumnName("UAA_AUDIT_LEVEL");
            entity.Property(e => e.UaaIheAudit).HasColumnName("UAA_IHE_AUDIT");
            entity.Property(e => e.UaaImDicomUid)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_IM_DICOM_UID");
            entity.Property(e => e.UaaPtId)
                .IsRequired()
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_PT_ID");
            entity.Property(e => e.UaaPtName)
                .IsRequired()
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_PT_NAME");
            entity.Property(e => e.UaaQueryString)
                .IsUnicode(false)
                .HasColumnName("UAA_QUERY_STRING");
            entity.Property(e => e.UaaSeDicomUid)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_SE_DICOM_UID");
            entity.Property(e => e.UaaStAccessionNumber)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_ST_ACCESSION_NUMBER");
            entity.Property(e => e.UaaStDicomUid)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_ST_DICOM_UID");
            entity.Property(e => e.UaaUser)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_USER");
            entity.Property(e => e.UaaUserDomain)
                .HasMaxLength(65)
                .IsUnicode(false)
                .HasColumnName("UAA_USER_DOMAIN");
            entity.Property(e => e.UaaVerifiedForDeletion).HasColumnName("UAA_VERIFIED_FOR_DELETION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TUserAudit> entity);
    }
}
