// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models.Configurations
{
    public partial class TVersionVerConfiguration : IEntityTypeConfiguration<TVersionVer>
    {
        public void Configure(EntityTypeBuilder<TVersionVer> entity)
        {
            entity
                .HasNoKey()
                .ToTable("T_VERSION_VER");

            entity.Property(e => e.VerBuildnumber).HasColumnName("VER_BUILDNUMBER");
            entity.Property(e => e.VerMajor).HasColumnName("VER_MAJOR");
            entity.Property(e => e.VerMinor).HasColumnName("VER_MINOR");
            entity.Property(e => e.VerRevision).HasColumnName("VER_REVISION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TVersionVer> entity);
    }
}
