// <auto-generated />
using System;
using Acuo.IHEAudit.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acuo.IHEAudit.DAL.Original.PostgreSQL
{
    [DbContext(typeof(AcuoMedIHEAuditContext))]
    [Migration("20240828111021_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TAcuoAudit", b =>
                {
                    b.Property<int>("AlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlId"));

                    b.Property<string>("AlAccessionNumber")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_ACCESSION_NUMBER");

                    b.Property<string>("AlAcuostoreApplicationName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("AL_ACUOSTORE_APPLICATION_NAME");

                    b.Property<string>("AlAcuostoreServerName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AL_ACUOSTORE_SERVER_NAME");

                    b.Property<string>("AlAcuostoreUserName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("AL_ACUOSTORE_USER_NAME");

                    b.Property<string>("AlAcuostoreUserPassword")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("AL_ACUOSTORE_USER_PASSWORD");

                    b.Property<DateTime>("AlAuditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AL_AUDIT_DATE");

                    b.Property<string>("AlComment")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AL_COMMENT");

                    b.Property<string>("AlDatabase")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_DATABASE");

                    b.Property<string>("AlDeletionSetId")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AL_DELETION_SET_ID");

                    b.Property<string>("AlEventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AL_EVENT_TYPE");

                    b.Property<string>("AlFileName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AL_FILE_NAME");

                    b.Property<Guid?>("AlIheId")
                        .HasColumnType("uuid")
                        .HasColumnName("AL_IHE_ID");

                    b.Property<string>("AlImSopinstanceUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_IM_SOPINSTANCE_UID");

                    b.Property<byte[]>("AlImageGuid")
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("AL_IMAGE_GUID")
                        .IsFixedLength();

                    b.Property<string>("AlMachine")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_MACHINE");

                    b.Property<string>("AlPtId")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_PT_ID");

                    b.Property<string>("AlPtName")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_PT_NAME");

                    b.Property<byte[]>("AlRecycleBinFolder")
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("AL_RECYCLE_BIN_FOLDER")
                        .IsFixedLength();

                    b.Property<bool>("AlRestore")
                        .HasColumnType("boolean")
                        .HasColumnName("AL_RESTORE");

                    b.Property<string>("AlRestoredAeName")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("AL_RESTORED_AE_NAME");

                    b.Property<DateTime?>("AlRestoredLastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AL_RESTORED_LAST_DATE");

                    b.Property<int?>("AlRestoredPort")
                        .HasColumnType("integer")
                        .HasColumnName("AL_RESTORED_PORT");

                    b.Property<string>("AlRestoredServer")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AL_RESTORED_SERVER");

                    b.Property<string>("AlSeDicomUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_SE_DICOM_UID");

                    b.Property<string>("AlSeModality")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("AL_SE_MODALITY");

                    b.Property<string>("AlSource")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_SOURCE");

                    b.Property<string>("AlStDicomUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_ST_DICOM_UID");

                    b.Property<string>("AlUser")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("AL_USER");

                    b.Property<bool>("AlVerifiedForDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("AL_VERIFIED_FOR_DELETION");

                    b.HasKey("AlId")
                        .HasName("PK_T_ACUO_AUDIT__Id");

                    b.HasIndex(new[] { "AlAuditDate", "AlEventType", "AlAcuostoreServerName" }, "IX_T_ACUO_AUDIT__AuditDate_EventType_ServerName")
                        .HasAnnotation("Npgsql:StorageParameter:fillfactor", 100)
                        .HasAnnotation("SqlServer:FillFactor", 100);

                    b.ToTable("T_ACUO_AUDIT", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CONFIG_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("ConfigDaysToKeepAcuoAudits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("CONFIG_DAYS_TO_KEEP_ACUO_AUDITS");

                    b.Property<int>("ConfigDaysToKeepAudits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("CONFIG_DAYS_TO_KEEP_AUDITS");

                    b.Property<int>("ConfigDaysToKeepDeletedImages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("CONFIG_DAYS_TO_KEEP_DELETED_IMAGES");

                    b.Property<int>("ConfigDaysToKeepUserAudits")
                        .HasColumnType("integer")
                        .HasColumnName("CONFIG_DAYS_TO_KEEP_USER_AUDITS");

                    b.Property<bool>("ConfigDeletionVerificationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("CONFIG_DELETION_VERIFICATION_REQUIRED");

                    b.Property<bool>("ConfigManualDeletionOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("CONFIG_MANUAL_DELETION_ONLY");

                    b.Property<int>("ConfigMinutesToKeepSyslogTasks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1440)
                        .HasColumnName("CONFIG_MINUTES_TO_KEEP_SYSLOG_TASKS");

                    b.Property<int>("ConfigSecondsToCheckForSyslogAudits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_AUDITS");

                    b.Property<int>("ConfigSecondsToCheckForSyslogChanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_CHANGES");

                    b.HasKey("ConfigId")
                        .HasName("PK_T_CONFIG__Id");

                    b.ToTable("T_CONFIG", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TEvent", b =>
                {
                    b.Property<int>("EvId")
                        .HasColumnType("integer")
                        .HasColumnName("EV_ID");

                    b.Property<int>("EvType")
                        .HasColumnType("integer")
                        .HasColumnName("EV_TYPE");

                    b.Property<string>("EvCodeSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EV_CODE_SYSTEM");

                    b.Property<string>("EvIdDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EV_ID_DESCRIPTION");

                    b.Property<bool>("EvLogCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("EV_LOG_CREATE");

                    b.Property<int>("EvLogCreateSupport")
                        .HasColumnType("integer")
                        .HasColumnName("EV_LOG_CREATE_SUPPORT");

                    b.Property<bool>("EvLogDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("EV_LOG_DELETE");

                    b.Property<int>("EvLogDeleteSupport")
                        .HasColumnType("integer")
                        .HasColumnName("EV_LOG_DELETE_SUPPORT");

                    b.Property<bool>("EvLogExecute")
                        .HasColumnType("boolean")
                        .HasColumnName("EV_LOG_EXECUTE");

                    b.Property<int>("EvLogExecuteSupport")
                        .HasColumnType("integer")
                        .HasColumnName("EV_LOG_EXECUTE_SUPPORT");

                    b.Property<bool>("EvLogRead")
                        .HasColumnType("boolean")
                        .HasColumnName("EV_LOG_READ");

                    b.Property<int>("EvLogReadSupport")
                        .HasColumnType("integer")
                        .HasColumnName("EV_LOG_READ_SUPPORT");

                    b.Property<bool>("EvLogUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("EV_LOG_UPDATE");

                    b.Property<int>("EvLogUpdateSupport")
                        .HasColumnType("integer")
                        .HasColumnName("EV_LOG_UPDATE_SUPPORT");

                    b.Property<string>("EvTypeDescription")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EV_TYPE_DESCRIPTION");

                    b.HasKey("EvId", "EvType")
                        .HasName("PK_T_EVENTS__Id_Type");

                    b.ToTable("T_EVENTS", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TIheAudit", b =>
                {
                    b.Property<Guid>("IheAuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("IHE_AUDIT_ID");

                    b.Property<string>("IheEventAction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("character(1)")
                        .HasColumnName("IHE_EVENT_ACTION")
                        .IsFixedLength();

                    b.Property<int>("IheEventId")
                        .HasColumnType("integer")
                        .HasColumnName("IHE_EVENT_ID");

                    b.Property<int?>("IheEventType")
                        .HasColumnType("integer")
                        .HasColumnName("IHE_EVENT_TYPE");

                    b.Property<DateTime>("IheLocalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("IHE_LOCAL_DATE");

                    b.Property<int>("IheSyslogSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("IHE_SYSLOG_SEVERITY");

                    b.Property<bool>("IheVerifiedForDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("IHE_VERIFIED_FOR_DELETION");

                    b.Property<byte[]>("IheXmlMessage")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("IHE_XML_MESSAGE");

                    b.HasKey("IheAuditId")
                        .HasName("PK_T_IHE_AUDIT__AuditId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex(new[] { "IheLocalDate" }, "IX_T_IHE_AUDIT__LocalDate")
                        .HasAnnotation("Npgsql:StorageParameter:fillfactor", 100)
                        .HasAnnotation("SqlServer:Clustered", true)
                        .HasAnnotation("SqlServer:FillFactor", 100);

                    b.ToTable("T_IHE_AUDIT", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TSyslog", b =>
                {
                    b.Property<Guid>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RS_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("RsClientCert")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RS_CLIENT_CERT");

                    b.Property<string>("RsHostid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RS_HOSTID");

                    b.Property<bool>("RsPause")
                        .HasColumnType("boolean")
                        .HasColumnName("RS_PAUSE");

                    b.Property<int>("RsPort")
                        .HasColumnType("integer")
                        .HasColumnName("RS_PORT");

                    b.Property<string>("RsServerCert")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RS_SERVER_CERT");

                    b.Property<bool?>("RsTlsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("RS_TLS_ENABLED");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("RS_TYPE");

                    b.HasKey("RsId")
                        .HasName("PK_T_SYSLOG__Id");

                    b.ToTable("T_SYSLOG", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TASK_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<Guid>("TaskIheAuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("TASK_IHE_AUDIT_ID");

                    b.Property<string>("TaskLastError")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TASK_LAST_ERROR");

                    b.Property<DateTime>("TaskQueuedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("TASK_QUEUED_TIME");

                    b.Property<int>("TaskRunCount")
                        .HasColumnType("integer")
                        .HasColumnName("TASK_RUN_COUNT");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer")
                        .HasColumnName("TASK_STATUS");

                    b.Property<Guid>("TaskTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("TASK_TARGET_ID");

                    b.Property<byte[]>("TaskXmlMessage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("image")
                        .HasColumnName("TASK_XML_MESSAGE")
                        .HasDefaultValueSql("(0x00)");

                    b.HasKey("TaskId")
                        .HasName("PK_T_TASKS__Id");

                    b.HasIndex(new[] { "TaskTargetId", "TaskIheAuditId" }, "IX_T_TASKS__TargetId_IheAuditId")
                        .HasAnnotation("Npgsql:StorageParameter:fillfactor", 100)
                        .HasAnnotation("SqlServer:FillFactor", 90);

                    b.ToTable("T_TASKS", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TUpgradeBitmask", b =>
                {
                    b.Property<string>("MskKeyWord")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("MSK_KeyWord");

                    b.Property<string>("MskDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("MSK_Description");

                    b.Property<int>("MskKeyType")
                        .HasColumnType("integer")
                        .HasColumnName("MSK_KeyType");

                    b.Property<int>("MskMaskInteger")
                        .HasColumnType("integer")
                        .HasColumnName("MSK_MaskInteger");

                    b.HasKey("MskKeyWord")
                        .HasName("PK_T_UPGRADE_BITMASK__KeyWord");

                    b.ToTable("T_UPGRADE_BITMASK", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TUpgradeDetail", b =>
                {
                    b.Property<int>("DtlIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DTL_Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DtlIdentity"));

                    b.Property<int>("DtlHstIdentity")
                        .HasColumnType("integer")
                        .HasColumnName("DTL_HST_Identity");

                    b.Property<short>("DtlRetry")
                        .HasColumnType("smallint")
                        .HasColumnName("DTL_Retry");

                    b.Property<string>("DtlTask")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DTL_Task");

                    b.Property<DateTime>("DtlUtcEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTL_UtcEndDate");

                    b.Property<DateTime>("DtlUtcStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTL_UtcStartDate");

                    b.HasKey("DtlIdentity")
                        .HasName("PK_T_UPGRADE_DETAIL__Identity");

                    b.HasIndex(new[] { "DtlTask", "DtlHstIdentity" }, "IX_T_UPGRADE_DETAIL__Task_HSTIdentity")
                        .HasAnnotation("Npgsql:StorageParameter:fillfactor", 100)
                        .HasAnnotation("SqlServer:FillFactor", 100);

                    b.ToTable("T_UPGRADE_DETAIL", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TUpgradeHistory", b =>
                {
                    b.Property<int>("HstIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HST_Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HstIdentity"));

                    b.Property<string>("HstByUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("HST_By_User");

                    b.Property<string>("HstComment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("HST_Comment");

                    b.Property<int>("HstNewBuild")
                        .HasColumnType("integer")
                        .HasColumnName("HST_New_Build");

                    b.Property<long>("HstNewDbSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L)
                        .HasColumnName("HST_New_DbSize");

                    b.Property<int>("HstNewMajor")
                        .HasColumnType("integer")
                        .HasColumnName("HST_New_Major");

                    b.Property<int>("HstNewMinor")
                        .HasColumnType("integer")
                        .HasColumnName("HST_New_Minor");

                    b.Property<int>("HstNewSp")
                        .HasColumnType("integer")
                        .HasColumnName("HST_New_SP");

                    b.Property<int>("HstNewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("HST_New_Status");

                    b.Property<int>("HstOldBuild")
                        .HasColumnType("integer")
                        .HasColumnName("HST_Old_Build");

                    b.Property<long>("HstOldDbSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L)
                        .HasColumnName("HST_Old_DbSize");

                    b.Property<int>("HstOldMajor")
                        .HasColumnType("integer")
                        .HasColumnName("HST_Old_Major");

                    b.Property<int>("HstOldMinor")
                        .HasColumnType("integer")
                        .HasColumnName("HST_Old_Minor");

                    b.Property<int>("HstOldSp")
                        .HasColumnType("integer")
                        .HasColumnName("HST_Old_SP");

                    b.Property<int>("HstOldStatus")
                        .HasColumnType("integer")
                        .HasColumnName("HST_Old_Status");

                    b.Property<string>("HstSqledition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("HST_SQLEdition");

                    b.Property<string>("HstSqlinstance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("HST_SQLInstance");

                    b.Property<string>("HstSqllevel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("HST_SQLLevel");

                    b.Property<string>("HstSqlmachine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("HST_SQLMachine");

                    b.Property<string>("HstSqlversion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("HST_SQLVersion");

                    b.Property<int>("HstState")
                        .HasColumnType("integer")
                        .HasColumnName("HST_State");

                    b.Property<DateTime>("HstUtcEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("HST_UtcEndDate");

                    b.Property<DateTime>("HstUtcStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("HST_UtcStartDate");

                    b.HasKey("HstIdentity")
                        .HasName("PK_T_UPGRADE_HISTORY__Identity");

                    b.ToTable("T_UPGRADE_HISTORY", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TUserAudit", b =>
                {
                    b.Property<Guid>("UaaAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UAA_AUDIT_ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<short?>("UaaAuditAction")
                        .HasColumnType("smallint")
                        .HasColumnName("UAA_AUDIT_ACTION");

                    b.Property<DateTime>("UaaAuditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UAA_AUDIT_DATE");

                    b.Property<short?>("UaaAuditLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("UAA_AUDIT_LEVEL");

                    b.Property<Guid?>("UaaIheAudit")
                        .HasColumnType("uuid")
                        .HasColumnName("UAA_IHE_AUDIT");

                    b.Property<string>("UaaImDicomUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_IM_DICOM_UID");

                    b.Property<string>("UaaPtId")
                        .IsRequired()
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_PT_ID");

                    b.Property<string>("UaaPtName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_PT_NAME");

                    b.Property<string>("UaaQueryString")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("UAA_QUERY_STRING");

                    b.Property<string>("UaaSeDicomUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_SE_DICOM_UID");

                    b.Property<string>("UaaStAccessionNumber")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_ST_ACCESSION_NUMBER");

                    b.Property<string>("UaaStDicomUid")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_ST_DICOM_UID");

                    b.Property<string>("UaaUser")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_USER");

                    b.Property<string>("UaaUserDomain")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("UAA_USER_DOMAIN");

                    b.Property<bool>("UaaVerifiedForDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("UAA_VERIFIED_FOR_DELETION");

                    b.HasKey("UaaAuditId");

                    b.HasIndex(new[] { "UaaAuditDate", "UaaVerifiedForDeletion" }, "IX_T_USER_AUDIT__AuditDate_Verified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UaaPtId" }, "IX_T_USER_AUDIT__PatientId");

                    b.HasIndex(new[] { "UaaPtName" }, "IX_T_USER_AUDIT__PatientName");

                    b.HasIndex(new[] { "UaaUser" }, "IX_T_USER_AUDIT__User");

                    b.ToTable("T_USER_AUDIT", (string)null);
                });

            modelBuilder.Entity("Acuo.IHEAudit.DAL.Models.TVersionVer", b =>
                {
                    b.Property<int>("VerBuildnumber")
                        .HasColumnType("integer")
                        .HasColumnName("VER_BUILDNUMBER");

                    b.Property<int>("VerMajor")
                        .HasColumnType("integer")
                        .HasColumnName("VER_MAJOR");

                    b.Property<int>("VerMinor")
                        .HasColumnType("integer")
                        .HasColumnName("VER_MINOR");

                    b.Property<int>("VerRevision")
                        .HasColumnType("integer")
                        .HasColumnName("VER_REVISION");

                    b.ToTable("T_VERSION_VER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
