// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Acuo.IHEAudit.DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Acuo.IHEAudit.DAL.Models
{
    public partial interface IAcuoMedIHEAuditContextProcedures
    {
        Task<int> GetSqlTransAppLockAsync(string Resource, int? TimeOut, OutputParameter<int?> p2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GrantRightsOnUpdateResult>> GrantRightsOnUpdateAsync(bool? AcuoOnly, byte? FixDbo, byte? FixMap, byte? FixUser, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PR_QU_GrantRightsToRolesResult>> PR_QU_GrantRightsToRolesAsync(bool? AcuoOnly, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PR_QU_RepairDatabaseResult>> PR_QU_RepairDatabaseAsync(bool? AcuoOnly, byte? FixDbo, byte? FixMap, byte? FixUser, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PR_QU_UPGRADE_SummaryResult>> PR_QU_UPGRADE_SummaryAsync(int? pMaxResults, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ReleaseSqlTransAppLockAsync(string Resource, OutputParameter<int?> p2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_AUDITS_DELETE_ACUO_AUDITSResult>> SP_AUDITS_DELETE_ACUO_AUDITSAsync(bool? DaysToMinutes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_AUDITS_DELETE_IHE_AUDITSAsync(bool? DaysToMinutes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_AUDITS_DELETE_USER_AUDITSAsync(bool? DaysToMinutes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_AUDITS_UPDATE_RECYLCE_BIN_PARMSAsync(int? AuditId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CONFIG_SELECTResult>> SP_CONFIG_SELECTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_EVENT_AUDIT_CHECKAsync(int? EV_ID, int? EV_TYPE, int? EV_ACTION, OutputParameter<int?> EV_SUPPORTED, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_IHEAUDIT_INSERTAsync(int? IHE_EVENT_ID, int? IHE_EVENT_TYPE, string IHE_ACTION_CODE, int? IHE_SYSLOG_SEVERITY, byte[] IHE_XML_MESSAGE, string ACUO_EVENT_TYPE, string ACUO_USER, string ACUO_PT_ID, string ACUO_PT_NAME, string ACUO_ST_DICOM_UID, string ACUO_SE_MODALITY, string ACUO_SE_DICOM_UID, string ACUO_IM_SOPINSTANCE_UID, string ACUO_FILE_NAME, string ACUO_SOURCE, string ACUO_MACHINE, string ACUO_DATABASE, string ACUO_COMMENTS, string ACUO_ACCESSION_NUMBER, string ACUO_ACUOSTORE_SERVER, string ACUO_ACUOSTORE_APPL, string ACUO_ACUOSTORE_USERNAME, string ACUO_ACUOSTORE_PASSWORD, byte[] ACUO_RECYCLE_BIN_FOLDER, byte[] ACUO_IMAGE_GUID, string AL_DELETION_SET_ID, string AL_QUERY_STRING, short? AL_AUDIT_LEVEL, short? AL_AUDIT_ACTION, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_TASKS_DELETEAsync(bool? DaysToMinutes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_TASKS_GET_BY_TARGET_IDResult>> SP_TASKS_GET_BY_TARGET_IDAsync(Guid? TARGET_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_TASKS_UPDATEAsync(int? taskId, int? taskStatus, string taskLastError, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> USP_RethrowErrorAsync(string pRoutine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
