// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acuo.IHEAudit.DAL.Models
{
    public partial class SP_CONFIG_SELECTResult
    {
        public int CONFIG_ID { get; set; }
        public int CONFIG_DAYS_TO_KEEP_AUDITS { get; set; }
        public int CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_CHANGES { get; set; }
        public int CONFIG_SECONDS_TO_CHECK_FOR_SYSLOG_AUDITS { get; set; }
        public int CONFIG_DAYS_TO_KEEP_ACUO_AUDITS { get; set; }
        public int CONFIG_MINUTES_TO_KEEP_SYSLOG_TASKS { get; set; }
        public int CONFIG_DAYS_TO_KEEP_DELETED_IMAGES { get; set; }
        public bool CONFIG_DELETION_VERIFICATION_REQUIRED { get; set; }
        public bool CONFIG_MANUAL_DELETION_ONLY { get; set; }
        public int CONFIG_DAYS_TO_KEEP_USER_AUDITS { get; set; }
    }
}
