// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acuo.IHEAudit.DAL.Models
{
    public partial class SP_TASKS_GET_BY_TARGET_IDResult
    {
        public int TASK_ID { get; set; }
        public Guid TASK_TARGET_ID { get; set; }
        public Guid TASK_IHE_AUDIT_ID { get; set; }
        public int TASK_STATUS { get; set; }
        public string TASK_LAST_ERROR { get; set; }
        public DateTime TASK_QUEUED_TIME { get; set; }
        public byte[] TASK_XML_MESSAGE { get; set; }
    }
}
