// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TAcuoAudit
{
    public int AlId { get; set; }

    public DateTime AlAuditDate { get; set; }

    public string AlEventType { get; set; }

    public string AlUser { get; set; }

    public string AlPtId { get; set; }

    public string AlPtName { get; set; }

    public string AlStDicomUid { get; set; }

    public string AlSeModality { get; set; }

    public string AlSeDicomUid { get; set; }

    public string AlImSopinstanceUid { get; set; }

    public string AlFileName { get; set; }

    public string AlSource { get; set; }

    public string AlMachine { get; set; }

    public string AlDatabase { get; set; }

    public string AlComment { get; set; }

    public Guid? AlIheId { get; set; }

    public string AlAccessionNumber { get; set; }

    public string AlAcuostoreServerName { get; set; }

    public string AlAcuostoreApplicationName { get; set; }

    public string AlAcuostoreUserName { get; set; }

    public string AlAcuostoreUserPassword { get; set; }

    public byte[] AlRecycleBinFolder { get; set; }

    public byte[] AlImageGuid { get; set; }

    public string AlDeletionSetId { get; set; }

    public bool AlVerifiedForDeletion { get; set; }

    public DateTime? AlRestoredLastDate { get; set; }

    public string AlRestoredServer { get; set; }

    public int? AlRestoredPort { get; set; }

    public string AlRestoredAeName { get; set; }

    public bool AlRestore { get; set; }
}