// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TConfig
{
    public int ConfigId { get; set; }

    public int ConfigDaysToKeepAudits { get; set; }

    public int ConfigSecondsToCheckForSyslogChanges { get; set; }

    public int ConfigSecondsToCheckForSyslogAudits { get; set; }

    public int ConfigDaysToKeepAcuoAudits { get; set; }

    public int ConfigMinutesToKeepSyslogTasks { get; set; }

    public int ConfigDaysToKeepDeletedImages { get; set; }

    public bool ConfigDeletionVerificationRequired { get; set; }

    public bool ConfigManualDeletionOnly { get; set; }

    public int ConfigDaysToKeepUserAudits { get; set; }
}