// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TEvent
{
    public int EvId { get; set; }

    public string EvCodeSystem { get; set; }

    public int EvType { get; set; }

    public string EvIdDescription { get; set; }

    public string EvTypeDescription { get; set; }

    public int EvLogCreateSupport { get; set; }

    public int EvLogReadSupport { get; set; }

    public int EvLogUpdateSupport { get; set; }

    public int EvLogDeleteSupport { get; set; }

    public int EvLogExecuteSupport { get; set; }

    public bool EvLogCreate { get; set; }

    public bool EvLogRead { get; set; }

    public bool EvLogUpdate { get; set; }

    public bool EvLogDelete { get; set; }

    public bool EvLogExecute { get; set; }
}