// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TSyslog
{
    public Guid RsId { get; set; }

    public string RsType { get; set; }

    public string RsHostid { get; set; }

    public int RsPort { get; set; }

    public bool RsPause { get; set; }

    public bool? RsTlsEnabled { get; set; }

    public string RsClientCert { get; set; }

    public string RsServerCert { get; set; }
}