// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TTask
{
    public int TaskId { get; set; }

    public Guid TaskTargetId { get; set; }

    public Guid TaskIheAuditId { get; set; }

    public int TaskStatus { get; set; }

    public string TaskLastError { get; set; }

    public DateTime TaskQueuedTime { get; set; }

    public byte[] TaskXmlMessage { get; set; }

    public int TaskRunCount { get; set; }
}