// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acuo.IHEAudit.DAL.Models;

public partial class TUpgradeHistory
{
    public int HstIdentity { get; set; }

    public string HstSqledition { get; set; }

    public string HstSqlversion { get; set; }

    public string HstSqllevel { get; set; }

    public string HstSqlmachine { get; set; }

    public string HstSqlinstance { get; set; }

    public DateTime HstUtcStartDate { get; set; }

    public DateTime HstUtcEndDate { get; set; }

    public int HstOldStatus { get; set; }

    public int HstOldMajor { get; set; }

    public int HstOldMinor { get; set; }

    public int HstOldSp { get; set; }

    public int HstOldBuild { get; set; }

    public long HstOldDbSize { get; set; }

    public int HstNewStatus { get; set; }

    public int HstNewMajor { get; set; }

    public int HstNewMinor { get; set; }

    public int HstNewSp { get; set; }

    public int HstNewBuild { get; set; }

    public long HstNewDbSize { get; set; }

    public string HstByUser { get; set; }

    public string HstComment { get; set; }

    public int HstState { get; set; }
}